### ISSUE TITLE
Feature Request: Auto import cron names in multi cron editor

### ISSUE THREAD

**Issue by vkaelin** [Crontap/crontap#13]
Hi 👋

I think it would be nice to have the options to auto import crontab names from the imported file in the [Multi cron editor](https://tool.crontap.com/cronjob-debugger/multiple-cronjobs).

Because for now if we have a lot of jobs we need to manually edit each name. It would be nice to have the file path as a default name.
<img width="1634" alt="image" src="https://github.com/Crontap/crontap/assets/33511688/cdc55762-5977-4c0c-9b1f-109c34b7f0cd">

**Comment by danmindru** [comment]
Thanks for the suggestion @vkaelin!
This should be available now. Let me know if it works as expected 🙌

**Comment by vkaelin** [comment]
Perfectly, thanks!
