### ISSUE TITLE
First of the month flows over to the second

### ISSUE THREAD

**Issue by SonkeWohler** [Crontap/crontap#2]
I don't think this is correct, but correct me if I'm wrong.

Current Date: 2023/01/22
Cron: `30 * 1 * *`

It shows up fine for 2023/02/01 and 2023/03/01, but for 2023/04/01 it skips `00:30`, and adds instead 2023/04/02 `00:30`.  It seems to do the same for all following months.

Is this an April fools thing?

[link](https://tool.crontap.com/cronjob-debugger?cron=30+*+1+*+*)

Screenshot:
![Screenshot_20230122-114828](https://user-images.githubusercontent.com/44615513/213909648-19bea046-eb29-4902-a54e-fa198eed6569.jpg)

**Comment by danmindru** [comment]
Thanks for the report @SonkeWohler!
Interesting find, seems like a DST issue.
On Mar 26 due to DST hours will be offset by +1h
Everything up from that date to Oct 29 has that issue. Then it works again afterwards :P 

I guess it would be reasonable to take that into account.
Will take a look at it!

**Comment by danmindru** [comment]
Hey @SonkeWohler, the April fools should be gone now :D 
Thanks again for reporting this.
<img width="1312" alt="Screenshot 2023-01-23 at 13 34 35" src="https://user-images.githubusercontent.com/1515742/214041043-430d57ce-5ba7-4029-9bde-757231aeaae0.png">
