### ISSUE TITLE
'undefined' in text summaries

### ISSUE THREAD

**Issue by george-hm** [Crontap/crontap#3]
In the text summaries for crons, on the home page, I see 'undefined' for days

Example link:
[https://tool.crontap.com/cronjob-debugger/?cron=0+7+*+*+MON-FRI+*](https://tool.crontap.com/cronjob-debugger/?cron=0+7+*+*+MON-FRI+*)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/24510197/214373751-86d4bca0-9ef5-423b-b29c-25600d14ddb6.png">

I do not see any errors in the developer console

Version information:
Browser: Microsoft Edge Version 109.0.1518.61
Operating System: macOS Ventura 13.1

**Comment by danmindru** [comment]
Hi @george-hm,
Thanks so much for reporting this! A fix has been deployed.
You can clear the cache & try it out or open the tool in a new incognito/private window. 

<img width="540" alt="Screenshot 2023-01-25 at 13 31 10" src="https://user-images.githubusercontent.com/1515742/214564211-21775eeb-f5d4-41ac-bfd7-f86c907f2e36.png">

Cheers,
Dan

**Comment by george-hm** [comment]
@danmindru can confirm it's now fixed for me, thanks!
