### ISSUE TITLE
Bug: */5 * * * * vs 5 minutes

### ISSUE THREAD

**Issue by francistogram** [Crontap/crontap#6]
These two unexpectedly do different things

### `*/5 * * * *`
Will post every 5 minutes at the 0 and 5 minute intervals
<img width="520" alt="image" src="https://github.com/Crontap/crontap/assets/3721449/375fa338-f97e-4637-8144-890603b7434c">

### 5 minutes
Will post every 5 minutes but unclear the starting point. I assume it's when the schedule was created but unclear until it's been scheduled
<img width="529" alt="image" src="https://github.com/Crontap/crontap/assets/3721449/247c61d3-1fc2-4ab2-893d-cd4c19daa228">

I'd personally prefer to use the human readable format but because of this limitation I end up writing everything using the cron syntax

**Comment by danmindru** [comment]
It would have a slightly different effect, the human readable syntax is 5 minutes from the point of submission, so say you submit the schedule at 21:23:05, the next will be at 21:28:05 and so on.

But it'll be excellent to convey this through the description indeed.

**Comment by francistogram** [comment]
Yeah I mean I'd expect them to be the same given that taking `*/5 * * * *` to human readable is "Every 5 minutes" but then going the other way and inputting every 5 minutes gives every 5 minutes but at a different interval

Also I think as a developer that for having things to be more predictable e.g. on a :00 or :05 is so much more preferable to every 5 minutes at the current starting point

**Comment by danmindru** [comment]
I see, that makes sense. It would require a start date then, because cron kind of has both start date and schedule at the same time :)
Added a new issue, but this might require a bit of a rework to get right (#8)

For now made the description more clear at least and made it a bit nicer to work with (see #7).
