### ISSUE TITLE
Feature Request: Auto Detect Cron Syntax

### ISSUE THREAD

**Issue by francistogram** [Crontap/crontap#7]
The default syntax is human readable but it's actually quite common to come with your own cron syntax e.g.
1. Migrating from a different cron schedule provider
2. Figuring out the schedule from https://tool.crontap.com/ and then using it

If a string is pasted in that matches a cron syntax would be nice for it to auto switch instead of showing an error
<img width="893" alt="image" src="https://github.com/Crontap/crontap/assets/3721449/4643f421-fb47-4e39-804c-792fbfde987b">

**Comment by danmindru** [comment]
Would it make sense to have Cron syntax as the default here? :)

**Comment by francistogram** [comment]
Tbh I'd probably use the human readable if I wasn't running into [this issue](https://github.com/Crontap/crontap/issues/6) but switching the default would alleviate my problem too but not sure if it's worse for your other customers

**Comment by danmindru** [comment]
switched the default and added detection :)

https://github.com/Crontap/crontap/assets/1515742/0231a2c9-4b33-4ea5-a427-8f958efb1ebc

**Comment by danmindru** [comment]
Released in v1.4.1 🎉

**Comment by francistogram** [comment]
Hell yea, y'all are quick!
